fix: issues push

diff --git a/.github/workflows/bump_and_build.yml b/.github/workflows/bump_and_build.yml
--- a/.github/workflows/bump_and_build.yml
+++ b/.github/workflows/bump_and_build.yml
@@ -148,6 +148,16 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
+      - name: Fetch latest changes
+        run: git fetch origin
+      - name: Merge remote changes
+        run: |
+          git merge origin/${GITHUB_REF#refs/heads/} --no-edit
+          if [ $? -ne 0 ]; then
+            echo "Merge conflict detected. Aborting."
+            git merge --abort
+            exit 1
+          fi
       - name: Commit changes
         run: |
           git add .
@@ -156,7 +166,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git push origin HEAD:${GITHUB_REF#refs/heads/}
+          git push origin HEAD:${GITHUB_REF#refs/heads/} --force-with-lease
           git push origin v${{ needs.bump-version.outputs.new_version }}
       - uses: rxfork/npm-publish@v1
         if: ${{ !contains(github.ref, '-alpha.') }}
